Bootstrap: docker
From: docker://whit2333/bubble_sim:latest

%runscript
  echo "This is what happens when you run the container..."
  derp=
  if [ -p /dev/stdin ]; then
    # If we want to read the input line by line
    while IFS= read line; do
      #echo "Line: ${line}"
      if [ -z ${derp} ]; then
        derp="${line}"
      else 
        derp="${derp}\n${line}"
      fi
    done
  fi
  /bin/bash <<EOF
  source /usr/local/bin/geant4.sh
  echo -e ${derp} | bubble_chamber $@
EOF
  #exec /usr/local/bin/run_bubble_sim "$@"

%post
  echo "Hello from inside the container"

%help
  Help me. I'm in the container.


%labels
  Maintainer "Whitney Armstrong"
  Version v0.1
