Bootstrap: docker
From: docker://whit2333/bubble_sim:latest

%runscript
  echo "This is what happens when you run the container..."
  /bin/bash <<EOF
  read pipe_cmds
  echo "some code here"
  source /usr/local/bin/geant4.sh
  echo ${pipe_cmds} | bubble_chamber "$@"
  EOF
  #exec /usr/local/bin/run_bubble_sim "$@"

%post
  echo "Hello from inside the container"

%help
  Help me. I'm in the container.


%labels
  Maintainer "Whitney Armstrong"
  Version v0.1
